name: pyWitnessAI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cmake
  - dlib
  - pip
  - pip:
      - mtcnn
      - retina-face
      - numpy==1.26.4
      - tensorflow==2.16.1
      - keras == 3.0.5